import type { Charm } from "@data/charms";
import type { Creature } from "@data/creatures";
import type { Perk } from "@data/perks";
import type { Shield } from "@data/shields";
import type { Spell, SpellRawEffective } from "@data/spells";
import type { Ammo, Weapon } from "@data/weapons";
import type { CreatureChoiceRef, PerkChoiceRef, SpellChoiceRef, WeaponChoiceRef } from "@lib/build-state";

export type WeaponChoice = WeaponChoiceRef & { weapon: Weapon; ammo?: Ammo; shield?: Shield };
export type PerkChoice = PerkChoiceRef & { perk: Perk };
export type SpellChoice = SpellChoiceRef & { spell: Spell };
export type SpellDamageChoice = SpellChoiceRef & { spellDamage: SpellRawEffective };
export type CreatureChoice = CreatureChoiceRef & { creature: Creature; charm?: Charm };

export type CharacterState = {
  flat: number;
  magicLevel: number;
  skill: number;
  weaponAttack: number;
  weaponDamage: number;
  critChance: number;
  critDamage: number;
  fatalChance: number;
  transcendenceChance: number;
  baseMagicLevel: number;
  axe: number;
  club: number;
  sword: number;
  fist: number;
  distance: number;
  shielding: number;
  fishing: number;
  shieldDef: number;
};

export type SpellState = CharacterState & {
  spell: Spell;
  basePower: number;
  runicIncrease: number;
  baseHarmonyBonus: number;
  armorPenetration: number;
  deathPierce: number;
  earthPierce: number;
  energyPierce: number;
  firePierce: number;
  holyPierce: number;
  icePierce: number;
  physicalPierce: number;
  damageAmphibic: number;
  damageAquatic: number;
  damageBird: number;
  damageConstruct: number;
  damageDemon: number;
  damageDragon: number;
  damageElemental: number;
  damageExtraDimensional: number;
  damageFey: number;
  damageGiant: number;
  damageHuman: number;
  damageHumanoid: number;
  damageInkborn: number;
  damageLycanthrope: number;
  damageMagical: number;
  damageMammal: number;
  damagePlant: number;
  damageReptile: number;
  damageSlime: number;
  damageUndead: number;
  damageVermin: number;
};
